name: Bump version and open PR

on: workflow_call

jobs:
  bump-and-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - id: before
        run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - run: npx semantic-release --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: dummy

      - id: after
        run: echo "version=$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"

      - if: ${{ steps.before.outputs.version == steps.after.outputs.version }}
        run: |
          echo "No new release detected."
          exit 0

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.after.outputs.version }}"
          BRANCH="release/bump-$VERSION"
          git push origin "HEAD:$BRANCH"
          gh pr create \
            --title "chore(release): $VERSION" \
            --body "Automated bump & changelog update" \
            --base main \
            --head "$BRANCH"
