name: Tests and Validations

on:
  workflow_call:
    inputs:
      ref:
        description: Git ref to check out.
        required: true
        type: string

permissions:
  contents: read

jobs:
  checks:
    name: Tests and Validations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run commitlint (PR range)
        if: github.event_name == 'pull_request'
        run: npx commitlint --from "${{ github.event.pull_request.base.sha }}" --to "${{ github.event.pull_request.head.sha }}" --verbose

      - name: Run commitlint (latest commit)
        if: github.event_name != 'pull_request'
        run: npx commitlint --last --verbose

      - name: Prettier check
        run: npm run prettier:check

      - name: Run tests with coverage check
        run: npm run test-coverage

  pr_title:
    name: PR Title Check
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Validate PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$PR_TITLE" | npx commitlint --verbose

  dummy_delay:
    name: Dummy Delay Check
    runs-on: ubuntu-latest
    steps:
      - name: Wait 10 seconds
        run: sleep 10
