name: CI Auto Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  release:
    uses: ./.github/workflows/semantic_auto_release.yml
    permissions:
      contents: write
      packages: write
    secrets: inherit
