name: Create Release PR

on:
  repository_dispatch:
    types: [create-release-pr]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Wait for branch registration
        run: sleep 15

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NOTES=$(cat release-notes.txt)
          PR_URL=$(gh pr create \
            --base main \
            --head ${{ github.event.client_payload.temp_branch }} \
            --title "chore(release): ${{ github.event.client_payload.version }}" \
            --body "$NOTES")
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
