name: Publish after bump PR merge

on:
  pull_request:
    types:
      - closed
    branches:
      - auto_release

jobs:
  publish:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/bump-') &&
      github.event.pull_request.user.login == 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: read

    steps:
      - name: Checkout merged commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Verify commit authors are automation bot only
        run: |
          for author in $(git log --pretty='%an' \
            "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.merge_commit_sha }}"); do
            if [ "$author" != "github-actions[bot]" ]; then
              echo "❌ Unauthorized commit author: $author"
              exit 1
            fi
          done

      - name: Check changed files are only release‑related
        run: |
          changed=$(git diff --name-only \
            "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.merge_commit_sha }}")
          echo "Changed files: $changed"
          for f in $changed; do
            case "$f" in
              package.json|package-lock.json|CHANGELOG.md) ;;
              *) echo "❌ Unauthorized file change detected: $f" && exit 1 ;;
            esac
          done

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Publish Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Delete bump branch
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh branch delete "${{ github.event.pull_request.head.ref }}" --yes
