name: Publish Package

on:
  push:
    branches:
      - main

permissions:
  contents: write # for GitHub Release
  packages: write
  id-token: write # required for npm Trusted Publishing

jobs:
  publish:
    if: >
      startsWith(github.event.head_commit.message, 'chore(release):') &&
      github.actor == 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Publish package via Trusted Publishing
        run: npm publish --provenance --access public

      - name: Create GitHub Release
        run: |
          NOTES=$(git log -1 --pretty=%B)
          VERSION=$(echo "$NOTES" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          gh release create "v$VERSION" \
            --title "v$VERSION" \
            --notes "$NOTES"
