name: Release Engine

on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run bump phase
        if: ${{ inputs.mode == 'bump' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          BRANCH="release/bump-${GITHUB_RUN_NUMBER}-${GITHUB_RUN_ATTEMPT}"
          git checkout -b "${BRANCH}"

          PHASE="BUMP" SR_BRANCH="${BRANCH}" npx semantic-release --no-ci --extends ./release.config.js

          VERSION="$(node -p "require('./package.json').version")"
          git push --set-upstream origin "${BRANCH}"

          gh pr create \
            --github-token "$GITHUB_TOKEN" \
            --base main \
            --head "${BRANCH}" \
            --title "chore(release): ${VERSION} [skip ci]" \
            --body "Automated release bump PR for ${VERSION}. This PR updates CHANGES.md and package files."

      - name: Run publish phase
        if: ${{ inputs.mode == 'publish' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          set -euo pipefail
          PHASE="PUBLISH" SR_BRANCH="main" npx semantic-release --no-ci --extends ./release.config.js
